[package]
name = "npc_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
npc_generator_core = {path = "../npc_generator_core" }
rand = "0.8.5"
ron = "0.8.1"
stderrlog = "0.6.0"
